version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "8888:8000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    restart: on-failure
    command: >
      sh -c "python manage.py wait_db && python manage.py migrate && 
      python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./postgres:/var/lib/postgres
    restart: on-failure