# Generated by Django 5.1.7 on 2025-04-19 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingmodel',
            options={'ordering': ('id',)},
        ),
    ]
