# Generated by Django 5.1.7 on 2025-05-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_bookingmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
