# Generated by Django 5.1.7 on 2025-03-30 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='FuelTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'fuel_types',
            },
        ),
        migrations.CreateModel(
            name='StatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TransmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'transmissions',
            },
        ),
        migrations.CreateModel(
            name='AdvertisementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=128)),
                ('car_model', models.CharField(max_length=128)),
                ('engine', models.DecimalField(decimal_places=2, max_digits=4)),
                ('price', models.FloatField()),
                ('price_period', models.CharField(max_length=128)),
                ('pledge', models.BooleanField()),
                ('purpose', models.CharField(max_length=128)),
                ('driver', models.BooleanField()),
                ('comment', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_user', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_category', to='advertisements.categorymodel')),
                ('fuel_type', models.ManyToManyField(related_name='advertisement_fuel', to='advertisements.fueltypemodel')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_status', to='advertisements.statusmodel')),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_transmission', to='advertisements.transmissionmodel')),
            ],
            options={
                'db_table': 'advertisements',
                'ordering': ('id',),
            },
        ),
    ]
