# Generated by Django 5.1.7 on 2025-04-07 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertisements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advertisementphotomodel',
            name='advert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='advertisements.advertisementmodel'),
        ),
        migrations.AddField(
            model_name='advertisementmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_category', to='advertisements.categorymodel'),
        ),
        migrations.AddField(
            model_name='advertisementmodel',
            name='fuel_type',
            field=models.ManyToManyField(related_name='advertisement_fuel', to='advertisements.fueltypemodel'),
        ),
        migrations.AddField(
            model_name='advertisementmodel',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_status', to='advertisements.statusmodel'),
        ),
        migrations.AddField(
            model_name='advertisementmodel',
            name='transmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_transmission', to='advertisements.transmissionmodel'),
        ),
    ]
