# Generated by Django 5.1.7 on 2025-04-01 21:59

import core.services.upload_car_photo_service
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementPhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to=core.services.upload_car_photo_service.upload_to)),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='advertisements.advertisementmodel')),
            ],
            options={
                'db_table': 'adverts_photo',
            },
        ),
    ]
