# Generated by Django 5.1.7 on 2025-04-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementmodel',
            name='mileage',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
