# Generated by Django 5.1.7 on 2025-04-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_advertisementmodel_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementmodel',
            name='vin',
            field=models.CharField(max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name='statusmodel',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
