# Generated by Django 5.1.7 on 2025-04-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0004_alter_advertisementmodel_vin_alter_statusmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementmodel',
            name='engine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
